### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/pro#8]
```
Starting process with command: `node server`
INFO: Renovate Pro starting
INFO: Renovate Pro is running in Evaluation mode
INFO: Using GitHub endpoint: https://github.example.com/api/v3
INFO: Read private key from disk
 (node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
   at validateInputs (/usr/src/app/server.js:1:13967)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
 (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have the environment variable `GITHUB_APP_KEY` set according to the [configuration instructions](https://github.com/renovatebot/pro/blob/master/docs/2-configuration.md#configure-renovate-pro), so I would assume Renovate would **not** try reading the key from disk.

Of course, that may, or may not be related at all to the error.

**Comment by rarkins** [comment]
@destroyerofbuilds could you try again with `latest`? I pushed it just now.

Also, if you set `LOG_LEVEL=debug` in env then you will get additional logs for times like this.
